# Workflow para desplegar Fundacion API
name: Build and deploy ASP.Net Core app to Azure Web App - fundacion-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: fundacion-api
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'
  PROJECT_PATH: 'Fundacion/Api/Api.csproj'  # Ruta específica al proyecto API

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Verify project structure
        run: |
          echo "=== Estructura del repositorio ==="
          ls -la
          echo "=== Contenido de la carpeta Fundacion ==="
          ls -la Fundacion/
          echo "=== Verificando proyecto API ==="
          ls -la Fundacion/Api/

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

      - name: Test (si tienes tests)
        run: |
          if [ -f "Fundacion/Api.Tests/Api.Tests.csproj" ]; then
            dotnet test Fundacion/Api.Tests/Api.Tests.csproj --no-build --verbosity normal --configuration Release
          else
            echo "No se encontraron tests, continuando..."
          fi

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} --no-build --configuration Release --output ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: .
