# Workflow corregido para la estructura de Fundacion
name: Build and deploy ASP.Net Core app to Azure Web App - fundacion-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: fundacion-api
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Debug - Show repository structure
        run: |
          echo "=== Root directory ==="
          ls -la
          echo "=== Fundacion folder ==="
          ls -la Fundacion/
          echo "=== Api folder ==="
          ls -la Fundacion/Api/
          echo "=== Looking for .csproj files ==="
          find . -name "*.csproj" -type f

      - name: Restore dependencies
        run: dotnet restore Fundacion/Api/Api.csproj

      - name: Build
        run: dotnet build Fundacion/Api/Api.csproj --no-restore --configuration Release

      - name: Publish
        run: dotnet publish Fundacion/Api/Api.csproj --no-build --configuration Release --output ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: .
